Repository brain-tec/server-backend, pull requests merged in 2022-12, with the labels that each got.

#181 Syncing from upstream OCA/server-backend (14.0)
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: 14.0

#182 Syncing from upstream OCA/server-backend (15.0)
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: 15.0

#183 Syncing from upstream OCA/server-backend (16.0)
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: 16.0

#184 Backmerge into project's branch
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: 15.0.project_sy_639
