Repository brain-tec/server-backend, pull requests merged in 2022-10, with the labels that each got.

#162 Syncing from upstream OCA/server-backend (12.0)
  pglogical/__manifest__.py
  pglogical/hooks.py
Labels: 12.0

#163 [t132118] import migration base_user_role_company
  base_user_role_company/README.rst
  base_user_role_company/__init__.py
  base_user_role_company/__manifest__.py
  base_user_role_company/controllers/__init__.py
  base_user_role_company/controllers/main.py
  base_user_role_company/i18n/base_user_role_company.pot
  base_user_role_company/i18n/it.po
  base_user_role_company/models/__init__.py
  base_user_role_company/models/ir_http.py
  base_user_role_company/models/role.py
  base_user_role_company/models/user.py
  base_user_role_company/readme/CONFIGURE.rst
  base_user_role_company/readme/CONTRIBUTORS.rst
  base_user_role_company/readme/DESCRIPTION.rst
  base_user_role_company/readme/USAGE.rst
  base_user_role_company/static/description/icon.png
  base_user_role_company/static/description/index.html
  base_user_role_company/tests/__init__.py
  base_user_role_company/tests/test_role_per_company.py
  base_user_role_company/views/role.xml
  setup/base_user_role_company/odoo/addons/base_user_role_company
  setup/base_user_role_company/setup.py
Labels: 15.0.project_sy_639.t132118

#164 [t132118] Add base_user_role_company module
  README.md
  base_user_role_company/README.rst
  base_user_role_company/__init__.py
  base_user_role_company/__manifest__.py
  base_user_role_company/controllers/__init__.py
  base_user_role_company/controllers/main.py
  base_user_role_company/i18n/base_user_role_company.pot
  base_user_role_company/i18n/it.po
  base_user_role_company/models/__init__.py
  base_user_role_company/models/ir_http.py
  base_user_role_company/models/role.py
  base_user_role_company/models/user.py
  base_user_role_company/readme/CONFIGURE.rst
  base_user_role_company/readme/CONTRIBUTORS.rst
  base_user_role_company/readme/DESCRIPTION.rst
  base_user_role_company/readme/USAGE.rst
  base_user_role_company/static/description/icon.png
  base_user_role_company/static/description/index.html
  base_user_role_company/tests/__init__.py
  base_user_role_company/tests/test_role_per_company.py
  base_user_role_company/views/role.xml
  setup/base_user_role_company/odoo/addons/base_user_role_company
  setup/base_user_role_company/setup.py
Labels: 15.0.project_sy_639

#166 Syncing from upstream OCA/server-backend (15.0)
  README.md
  base_import_match/__manifest__.py
  base_import_match/models/base_import.py
Labels: 15.0

#168 Syncing from upstream OCA/server-backend (14.0)
  README.md
  base_user_role/README.rst
  base_user_role/__manifest__.py
  base_user_role/static/description/index.html
Labels: 14.0

#169 Syncing from upstream OCA/server-backend (15.0)
  README.md
  base_user_role/README.rst
  base_user_role/__manifest__.py
  base_user_role/static/description/index.html
  base_user_role/tests/test_user_role.py
Labels: 15.0

#171 Backmerge from 15.0 into 15.0.project_SY_639
  README.md
  base_import_match/__manifest__.py
  base_import_match/models/base_import.py
  base_user_role/README.rst
  base_user_role/__manifest__.py
  base_user_role/static/description/index.html
  base_user_role/tests/test_user_role.py
Labels: 15.0.project_sy_639
