Repository brain-tec/server-backend, pull requests merged in 2022-02, with the labels that each got.

#131 Syncing from upstream OCA/server-backend (13.0)
  server_action_navigate/README.rst
  server_action_navigate/__init__.py
  server_action_navigate/__manifest__.py
  server_action_navigate/demo/ir_actions_server.xml
  server_action_navigate/i18n/fr.po
  server_action_navigate/i18n/server_action_navigate.pot
  server_action_navigate/models/__init__.py
  server_action_navigate/models/ir_actions_server.py
  server_action_navigate/models/ir_actions_server_navigate_line.py
  server_action_navigate/readme/CONFIGURE.rst
  server_action_navigate/readme/CONTRIBUTORS.rst
  server_action_navigate/readme/DESCRIPTION.rst
  server_action_navigate/readme/USAGE.rst
  server_action_navigate/security/ir.model.access.csv
  server_action_navigate/static/description/icon.png
  server_action_navigate/static/description/index.html
  server_action_navigate/static/description/ir_actions_server_form.png
  server_action_navigate/static/description/product_product_tree.png
  server_action_navigate/static/description/sale_order_tree.png
  server_action_navigate/tests/__init__.py
  server_action_navigate/tests/test_module.py
  server_action_navigate/views/view_ir_actions_server.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/server_action_navigate/odoo/addons/server_action_navigate
  setup/server_action_navigate/setup.py
Labels: 13.0

#133 Syncing from upstream OCA/server-backend (12.0)
  base_external_dbsource/i18n/es.po
  base_user_role/i18n/de.po
  base_user_role_company/i18n/de.po
  base_user_role_history/i18n/de.po
  base_user_role_profile/i18n/de.po
Labels: 12.0

#134 Syncing from upstream OCA/server-backend (14.0)
  base_user_role/i18n/it.po
  base_user_role_company/i18n/it.po
Labels: 14.0

#135 15.0.project ge 578 base user role company
  base_user_role_company/README.rst
  base_user_role_company/__init__.py
  base_user_role_company/__manifest__.py
  base_user_role_company/i18n/base_user_role_company.pot
  base_user_role_company/models/__init__.py
  base_user_role_company/models/ir_http.py
  base_user_role_company/models/role.py
  base_user_role_company/readme/CONFIGURE.rst
  base_user_role_company/readme/CONTRIBUTORS.rst
  base_user_role_company/readme/DESCRIPTION.rst
  base_user_role_company/readme/USAGE.rst
  base_user_role_company/static/description/icon.png
  base_user_role_company/static/description/index.html
  base_user_role_company/tests/__init__.py
  base_user_role_company/tests/test_role_per_company.py
  base_user_role_company/views/role.xml
  setup/base_user_role_company/odoo/addons/base_user_role_company
  setup/base_user_role_company/setup.py
Labels: 15.0.project_ge_578
