Repository brain-tec/server-backend, pull requests merged in 2023-07, with the labels that each got.

#242 Syncing from upstream OCA/server-backend (15.0)
  README.md
  base_external_dbsource_sap_hana/README.rst
  base_external_dbsource_sap_hana/__init__.py
  base_external_dbsource_sap_hana/__manifest__.py
  base_external_dbsource_sap_hana/demo/base_external_dbsource.xml
  base_external_dbsource_sap_hana/i18n/base_external_dbsource_sap_hana.pot
  base_external_dbsource_sap_hana/models/__init__.py
  base_external_dbsource_sap_hana/models/base_external_dbsource.py
  base_external_dbsource_sap_hana/readme/CONFIGURE.rst
  base_external_dbsource_sap_hana/readme/CONTRIBUTORS.rst
  base_external_dbsource_sap_hana/readme/DESCRIPTION.rst
  base_external_dbsource_sap_hana/readme/INSTALL.rst
  base_external_dbsource_sap_hana/readme/USAGE.rst
  base_external_dbsource_sap_hana/static/description/icon.png
  base_external_dbsource_sap_hana/static/description/index.html
  base_external_dbsource_sap_hana/tests/__init__.py
  base_external_dbsource_sap_hana/tests/test_base_external_dbsource_sap_hana.py
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_external_dbsource_sap_hana/odoo/addons/base_external_dbsource_sap_hana
  setup/base_external_dbsource_sap_hana/setup.py
Labels: 15.0

#243 Syncing from upstream OCA/server-backend (13.0)
  .pre-commit-config.yaml
  base_external_dbsource/__manifest__.py
  base_external_dbsource/models/base_external_dbsource.py
  base_external_dbsource/tests/test_base_external_dbsource.py
  base_external_dbsource_mssql/__manifest__.py
  base_external_dbsource_mssql/models/base_external_dbsource.py
  base_external_dbsource_mssql/tests/test_base_external_dbsource.py
  base_external_dbsource_mysql/__manifest__.py
  base_external_dbsource_mysql/models/base_external_dbsource.py
  base_external_dbsource_mysql/tests/test_base_external_dbsource.py
  base_external_dbsource_sqlite/__manifest__.py
  base_external_dbsource_sqlite/models/base_external_dbsource.py
  base_external_dbsource_sqlite/tests/test_base_external_dbsource.py
  base_external_system/__manifest__.py
  base_external_system/models/external_system.py
  base_external_system/tests/test_external_system.py
  base_global_discount/__manifest__.py
  base_global_discount/models/global_discount.py
  base_import_match/__manifest__.py
  base_import_match/models/base.py
  base_import_match/models/base_import.py
  base_import_match/tests/test_import.py
  base_user_role/__manifest__.py
  base_user_role/models/role.py
  base_user_role/views/user.xml
  server_action_navigate/__manifest__.py
  server_action_navigate/models/ir_actions_server_navigate_line.py
Labels: 13.0

#244 Syncing from upstream OCA/server-backend (12.0)
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  base_external_dbsource/__manifest__.py
  base_external_dbsource/tests/test_base_external_dbsource.py
  base_external_dbsource_mssql/__manifest__.py
  base_external_dbsource_mssql/readme/ROADMAP.rst
  base_external_dbsource_mysql/__manifest__.py
  base_external_dbsource_mysql/readme/CONFIGURE.rst
  base_external_dbsource_sqlite/__manifest__.py
  base_import_match/__manifest__.py
  base_suspend_security/__manifest__.py
  base_user_role/__manifest__.py
  base_user_role/readme/CONFIGURE.rst
  base_user_role_history/__manifest__.py
  requirements.txt
  server_action_navigate/__manifest__.py
  server_action_navigate/i18n/fr.po
Labels: 12.0

#245 Syncing from upstream OCA/server-backend (14.0)
  README.md
  base_user_role/__manifest__.py
  base_user_role/views/user.xml
Labels: 14.0

#246 Syncing from upstream OCA/server-backend (15.0)
  README.md
  base_user_role/__manifest__.py
  base_user_role/views/user.xml
Labels: 15.0

#247 Syncing from upstream OCA/server-backend (16.0)
  README.md
  base_user_role/__manifest__.py
  base_user_role/views/user.xml
Labels: 16.0

#248 Syncing from upstream OCA/server-backend (16.0)
  base_user_role/i18n/it.po
Labels: 16.0

#250 Syncing from upstream OCA/server-backend (16.0)
  README.md
  base_portal_type/README.rst
  base_portal_type/__init__.py
  base_portal_type/__manifest__.py
  base_portal_type/data/ir_module_category.xml
  base_portal_type/demo/res_groups.xml
  base_portal_type/i18n/base_portal_type.pot
  base_portal_type/models/__init__.py
  base_portal_type/models/res_groups.py
  base_portal_type/readme/CONTRIBUTORS.rst
  base_portal_type/readme/DESCRIPTION.rst
  base_portal_type/readme/ROADMAP.rst
  base_portal_type/readme/USAGE.rst
  base_portal_type/static/description/icon.png
  base_portal_type/static/description/index.html
  base_portal_type/tests/__init__.py
  base_portal_type/tests/test_base_portal_type.py
  base_user_role/i18n/fr.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_portal_type/odoo/addons/base_portal_type
  setup/base_portal_type/setup.py
Labels: 16.0

#251 Update project branch
  README.md
  base_external_dbsource_sap_hana/README.rst
  base_external_dbsource_sap_hana/__init__.py
  base_external_dbsource_sap_hana/__manifest__.py
  base_external_dbsource_sap_hana/demo/base_external_dbsource.xml
  base_external_dbsource_sap_hana/i18n/base_external_dbsource_sap_hana.pot
  base_external_dbsource_sap_hana/models/__init__.py
  base_external_dbsource_sap_hana/models/base_external_dbsource.py
  base_external_dbsource_sap_hana/readme/CONFIGURE.rst
  base_external_dbsource_sap_hana/readme/CONTRIBUTORS.rst
  base_external_dbsource_sap_hana/readme/DESCRIPTION.rst
  base_external_dbsource_sap_hana/readme/INSTALL.rst
  base_external_dbsource_sap_hana/readme/USAGE.rst
  base_external_dbsource_sap_hana/static/description/icon.png
  base_external_dbsource_sap_hana/static/description/index.html
  base_external_dbsource_sap_hana/tests/__init__.py
  base_external_dbsource_sap_hana/tests/test_base_external_dbsource_sap_hana.py
  base_user_role/__manifest__.py
  base_user_role/i18n/it.po
  base_user_role/views/user.xml
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_external_dbsource_sap_hana/odoo/addons/base_external_dbsource_sap_hana
  setup/base_external_dbsource_sap_hana/setup.py
Labels: 15.0.project_sy_639

#252 Syncing from upstream OCA/server-backend (16.0)
  base_import_match/i18n/it.po
Labels: 16.0
