Repository brain-tec/server-backend, pull requests merged in 2023-03, with the labels that each got.

#196 Syncing from upstream OCA/server-backend (16.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
Labels: 16.0

#197 Syncing from upstream OCA/server-backend (11.0)
  base_import_match/i18n/it.po
Labels: 11.0

#198 Syncing from upstream OCA/server-backend (14.0)
  base_user_role_company/i18n/it.po
Labels: 14.0

#200 Syncing from upstream OCA/server-backend (15.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: 15.0

#201 Syncing from upstream OCA/server-backend (12.0)
  base_suspend_security/i18n/it.po
Labels: 12.0

#202 Syncing from upstream OCA/server-backend (14.0)
  base_external_dbsource/i18n/it.po
Labels: 14.0

#203 Syncing from upstream OCA/server-backend (15.0)
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
Labels: 15.0

#204 Update project branch with latest contents of 15.0
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
Labels: 15.0.project_sy_639

#205 Syncing from upstream OCA/server-backend (11.0)
  base_import_match/i18n/it.po
Labels: 11.0

#206 Syncing from upstream OCA/server-backend (12.0)
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
  base_user_role/i18n/it.po
Labels: 12.0

#207 Syncing from upstream OCA/server-backend (13.0)
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
  base_user_role/i18n/it.po
Labels: 13.0

#208 Syncing from upstream OCA/server-backend (14.0)
  base_import_match/i18n/it.po
  base_user_role/i18n/it.po
Labels: 14.0

#209 Syncing from upstream OCA/server-backend (15.0)
  base_user_role/i18n/it.po
Labels: 15.0
