Repository brain-tec/server-backend, pull requests merged in 2023-05, with the labels that each got.

#230 Syncing from upstream OCA/server-backend (14.0)
  base_user_role/i18n/pt_BR.po
  base_user_role_company/i18n/pt_BR.po
Labels: 14.0

#229 Update project branch
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
  base_user_role/i18n/it.po
Labels: 15.0.project_sy_639

#231 Syncing from upstream OCA/server-backend (15.0)
  base_user_role/i18n/it.po
Labels: 15.0

#232 Syncing from upstream OCA/server-backend (11.0)
  base_external_dbsource/i18n/it.po
  base_user_role/i18n/it.po
Labels: 11.0
