Repository brain-tec/server-backend, pull requests merged in 2023-04, with the labels that each got.

#210 Syncing from upstream OCA/server-backend (11.0)
  base_import_match/i18n/sl.po
Labels: 11.0

#211 Syncing from upstream OCA/server-backend (14.0)
  base_external_dbsource/i18n/sl.po
  base_import_match/i18n/sl.po
  base_user_role/i18n/sl.po
Labels: 14.0

#212 Syncing from upstream OCA/server-backend (15.0)
  base_import_match/i18n/sl.po
  base_user_role/i18n/sl.po
Labels: 15.0

#214 Syncing from upstream OCA/server-backend (16.0)
  README.md
  base_external_dbsource_sqlite/README.rst
  base_external_dbsource_sqlite/__init__.py
  base_external_dbsource_sqlite/__manifest__.py
  base_external_dbsource_sqlite/demo/base_external_dbsource.xml
  base_external_dbsource_sqlite/i18n/base_external_dbsource_sqlite.pot
  base_external_dbsource_sqlite/i18n/de.po
  base_external_dbsource_sqlite/i18n/es.po
  base_external_dbsource_sqlite/i18n/hr.po
  base_external_dbsource_sqlite/i18n/nl_NL.po
  base_external_dbsource_sqlite/i18n/pt_BR.po
  base_external_dbsource_sqlite/i18n/sl.po
  base_external_dbsource_sqlite/i18n/tr.po
  base_external_dbsource_sqlite/models/__init__.py
  base_external_dbsource_sqlite/models/base_external_dbsource.py
  base_external_dbsource_sqlite/readme/CONFIGURE.rst
  base_external_dbsource_sqlite/readme/CONTRIBUTORS.rst
  base_external_dbsource_sqlite/readme/DESCRIPTION.rst
  base_external_dbsource_sqlite/readme/INSTALL.rst
  base_external_dbsource_sqlite/readme/ROADMAP.rst
  base_external_dbsource_sqlite/readme/USAGE.rst
  base_external_dbsource_sqlite/static/description/icon.png
  base_external_dbsource_sqlite/static/description/index.html
  base_external_dbsource_sqlite/tests/__init__.py
  base_external_dbsource_sqlite/tests/test_base_external_dbsource.py
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_external_dbsource_sqlite/odoo/addons/base_external_dbsource_sqlite
  setup/base_external_dbsource_sqlite/setup.py
Labels: 16.0

#215 Syncing from upstream OCA/server-backend (11.0)
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
  base_user_role/i18n/it.po
Labels: 11.0

#216 Syncing from upstream OCA/server-backend (12.0)
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
  base_user_role/i18n/it.po
Labels: 12.0

#217 Syncing from upstream OCA/server-backend (13.0)
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
  base_user_role/i18n/it.po
Labels: 13.0

#219 Syncing from upstream OCA/server-backend (15.0)
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
  base_user_role/i18n/it.po
Labels: 15.0

#220 Syncing from upstream OCA/server-backend (16.0)
  base_external_dbsource/i18n/it.po
Labels: 16.0

#221 Syncing from upstream OCA/server-backend (16.0)
  README.md
  base_external_dbsource/i18n/sl.po
  base_external_dbsource_mssql/README.rst
  base_external_dbsource_mssql/__init__.py
  base_external_dbsource_mssql/__manifest__.py
  base_external_dbsource_mssql/demo/base_external_dbsource.xml
  base_external_dbsource_mssql/i18n/base_external_dbsource_mssql.pot
  base_external_dbsource_mssql/i18n/de.po
  base_external_dbsource_mssql/i18n/es.po
  base_external_dbsource_mssql/i18n/hr.po
  base_external_dbsource_mssql/i18n/nl_NL.po
  base_external_dbsource_mssql/i18n/pt_BR.po
  base_external_dbsource_mssql/i18n/sl.po
  base_external_dbsource_mssql/i18n/tr.po
  base_external_dbsource_mssql/models/__init__.py
  base_external_dbsource_mssql/models/base_external_dbsource.py
  base_external_dbsource_mssql/readme/CONFIGURE.rst
  base_external_dbsource_mssql/readme/CONTRIBUTORS.rst
  base_external_dbsource_mssql/readme/DESCRIPTION.rst
  base_external_dbsource_mssql/readme/INSTALL.rst
  base_external_dbsource_mssql/readme/ROADMAP.rst
  base_external_dbsource_mssql/readme/USAGE.rst
  base_external_dbsource_mssql/static/description/icon.png
  base_external_dbsource_mssql/static/description/index.html
  base_external_dbsource_mssql/tests/__init__.py
  base_external_dbsource_mssql/tests/test_base_external_dbsource.py
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_external_dbsource_mssql/odoo/addons/base_external_dbsource_mssql
  setup/base_external_dbsource_mssql/setup.py
Labels: 16.0

#222 Syncing from upstream OCA/server-backend (14.0)
  base_user_role/i18n/it.po
Labels: 14.0

#223 Update project branch with the newest 15.0
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
  base_import_match/i18n/sl.po
  base_user_role/i18n/it.po
  base_user_role/i18n/sl.po
Labels: 15.0.project_sy_639

#224 Syncing from upstream OCA/server-backend (12.0)
  base_user_role/i18n/it.po
Labels: 12.0

#225 Syncing from upstream OCA/server-backend (13.0)
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
  base_user_role/i18n/it.po
Labels: 13.0

#226 Syncing from upstream OCA/server-backend (14.0)
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
Labels: 14.0

#227 Syncing from upstream OCA/server-backend (15.0)
  base_external_dbsource/i18n/it.po
  base_import_match/i18n/it.po
  base_user_role/i18n/it.po
Labels: 15.0

#228 Syncing from upstream OCA/server-backend (16.0)
  base_external_dbsource/i18n/it.po
Labels: 16.0
